apiVersion: v1
kind: ConfigMap
metadata:
  name: trzenaro-mockserver
data:
  mockserverConfig: |-
    {
      "sessionsDirectory": "./sessions",
      "api": { "port": 3050 },
      "server": { "port": 3000 },
      "proxy": {
        "recordingDirectory": "./proxy",
        "prefix": [
          { "path": "/path-one", "proxyPass": "https://server-one.com" },
          { "path": "/path-two", "proxyPass": "https://server-two.com" },
          { "path": "/path-three", "proxyPass": "https://server-three.com", "rewrite": "/" }
        ]
      }
    }

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trzenaro-mockserver
spec:
  selector:
    matchLabels:
      app: trzenaro-mockserver
  serviceName: trzenaro-mockserver
  replicas: 1
  template:
    metadata:
      labels:
        app: trzenaro-mockserver
    spec:
      containers:
        - name: trzenaro-mockserver
          image: trzenaro/ezmockserver:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
            - containerPort: 3050
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "384Mi"
              cpu: "500m"
          volumeMounts:
            - name: sessions-data
              mountPath: /app/mockserver/sessions
            - name: proxy-data
              mountPath: /app/mockserver/proxy
            - name: mockserver-config
              mountPath: /app/mockserver/mockserver.json
              subPath: mockserverConfig
      volumes:
        - name: sessions-data
          emptyDir: {}
        - name: proxy-data
          emptyDir: {}
        - name: mockserver-config
          configMap:
            name: trzenaro-mockserver

---
apiVersion: v1
kind: Service
metadata:
  name: trzenaro-mockserver
  labels:
    app: trzenaro-mockserver
spec:
  ports:
    - port: 3000
      protocol: TCP
      name: server
      targetPort: 3000
    - port: 3050
      protocol: TCP
      name: api
      targetPort: 3050
  selector:
    app: trzenaro-mockserver

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: trzenaro-mockserver
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /mockserver/server(/|$)(.*)
            backend:
              serviceName: trzenaro-mockserver
              servicePort: 3000
            pathType: Prefix
          - path: /mockserver/api(/|$)(.*)
            backend:
              serviceName: trzenaro-mockserver
              servicePort: 3050
            pathType: Prefix
